/** One-sentence summary per special tower, shown on recipe cards instead of the full stat list. */
export const BLURB: Record<string, string> = {
  Silver: 'Slows the enemies it hits.',
  'Silver Knight': 'Splash damage that also slows.',
  'Pink Diamond': 'Big hitter with critical strikes.',
  'Huge Pink Diamond': 'Critical splash damage that slows.',
  'Koh-i-noor Diamond': 'Critical splash damage that shreds armor.',
  Malachite: 'Hits up to 3 enemies at once.',
  'Vivid Malachite': 'Hits up to 5 enemies at once.',
  'Uranium-238': 'Irradiates up to 10 enemies at once.',
  'Uranium-235': 'Irradiates up to 10 enemies at once.',
  'Depleted-Kyparium': 'Irradiates up to 10 enemies at once.',
  'Asteriated Ruby': 'Burns nearby enemies every second.',
  Volcano: 'Burns nearby enemies hard every second.',
  Bloodstone: 'Attacks can spark chain lightning.',
  'Antique Bloodstone': 'Forked lightning plus a strong burn aura.',
  'The Crown Prince': 'Forked lightning, huge burn and lethal poison.',
  Jade: 'Poisons the enemies it hits.',
  Quartz: 'Weakens and slows flying enemies.',
  'Grey Jade': 'Poisons enemies and extends nearby towers’ range.',
  'Monkey King Jade': 'Extends range and lets nearby towers ignore evasion.',
  'Diamond Cullinan': 'Critical hits; nearby towers gain range and ignore evasion.',
  'Lucky Chinese Jade': 'Poisons, slows flyers and can heal the castle.',
  'Charming Lazurite': 'Strips armor, speed and magic resist from flyers.',
  'Golden Jubilee': 'Anti-air tower that adds magic damage to every attack.',
  Gold: 'Reduces the target’s armor.',
  'Egypt Gold': 'Reduces armor; nearby kills can pay 10× gold.',
  'Dark Emerald': 'Attacks can stun.',
  'Emerald Golem': 'Stuns, reduces armor and can petrify crowds.',
  'Paraiba Tourmaline': 'Reduces armor of nearby enemies.',
  'Elaborately Carved Tourmaline': 'Stuns and strips armor from nearby enemies.',
  'Sapphire Star Of Adam': 'Poisons, shreds armor and chills nearby enemies.',
  'Deepsea Pearl': 'Protects nearby towers from magic.',
  "Chrysoberyl Cat's Eye": 'Increases damage and attack speed of nearby towers.',
  'Red Coral': 'Boosts nearby towers’ damage and speed, and resists magic.',
  'Natural Zumurud': 'A plain, sturdy attacker.',
  'Carmen-Lucia': 'Massively boosts nearby towers’ damage and attack speed.',
  'Yellow Sapphire': 'Slows nearby enemies.',
  "Northern Saber's Eye": 'Slows nearby enemies; pedals can trigger frost balls.',
  'Star Sapphire': 'Heavy slows and an attack speed aura.',
  Obsidian: 'Wide splash damage that slows.',
  Agate: 'Hits up to 5 enemies at once.',
  'Fantastic Miss Shrimp': 'Lightning attacks, but sometimes sulks and stops.',
  Geluanshi: 'Shreds armor, especially on flyers.',
  'The Burning Stone': 'Burns nearby enemies with enormous damage.',
  'The Great Stone': 'Critical hits with full-damage splash.',
  'Black Opal': 'Big hitter with critical strikes.',
  Ehome: 'Huge attack speed aura for nearby towers.',
  'Wings Stone': 'Full-damage splash over a wide area.',
  'Regent Diamond': 'Critical splash that also cuts 2% of max HP per hit.',
  'Kyparium Core': 'Irradiates 15 enemies, each hit cutting 2% of max HP.',
  'The Blood King': 'Forked lightning and burns; grows stronger with every kill.',
  'Cullinan Heart': 'Colossal crits whose damage grows with every kill.',
  'Star of Eden': 'Freezing poison that cuts max HP and grows with kills.',
};
